name: Terraform Validate
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform fmt
        run: terraform fmt -recursive -check

      - name: Terraform validate (envs/dev)
        working-directory: ./envs/dev
        run: |
          terraform init -backend=false
          terraform validate
